version: "3.8"

services:
    db:
        image: postgres:14-alpine
        container_name: airbnb-db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_DRIVER=${POSTGRES_DRIVER}
        ports:
            - 5432:5432
        expose:
            - 5432

volumes:
    postgres_data:

