version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings
        description: This is RAW listings data from AIRBNB

      - name: hosts
        identifier: raw_hosts
        description: This is RAW hosts data from AIRBNB

      - name: reviews
        identifier: raw_reviews
        description: This is RAW reviews data from AIRBNB
        loaded_at_field: date
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}
